---
- name: Deploy simple PHP Docker app
  hosts: docker_hosts
  become: true

  vars:
    app_dir: "/opt/php_todo_docker"

  tasks:
    # 1. Clone repository
    - name: Clone repository
      git:
        repo: "https://github.com/hpaanonlineuniversity/php_todo_docker.git"
        dest: "{{ app_dir }}"
        update: yes

    # 2. Run docker compose
    - name: Start Docker Compose
      shell: |
        cd {{ app_dir }}
        docker compose up -d
      register: compose_result

    - name: Show compose output
      debug:
        var: compose_result.stdout_lines
    # 3. Verify
    - name: Check containers
      shell: docker ps
      register: containers

    - name: Show container status
      debug:
        msg: "Running containers:\n{{ containers.stdout }}"
